version: "3.7"
services:
  maria_db:
    image: "mariadb:10.9"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: testing
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
